### ISSUE TITLE
wiringpi is deprecated

### ISSUE THREAD

**Issue by eshaham** [samsonmking/epaper.js#47]
when trying to run the commands in the readme, I could not get `wiringpi` to install:

```
sudo apt-get install -y wiringpi
```

from what I'm reading, it is being deprecated
are there any alternatives?

**Comment by samsonmking** [comment]
Hi @eshaham, the deprecation of `wiringpi` had been on my radar, but I didn't realize it was removed from the apt repositories. I think it'll be possible to switch to the BCM2835 libraries instead of `wiringpi`.

What version of Raspberry Pi OS and what type of model of Raspberry Pi are you using? 

In the meantime, can you manually download / install as a workaround?
```
cd /tmp
wget https://project-downloads.drogon.net/wiringpi-latest.deb
sudo dpkg -i wiringpi-latest.deb
#You will get 2.52 information if you've installed it correctly
gpio -v
```

**Comment by samsonmking** [comment]
I'm currently working on a version 2.0, that I hope to release in the next couple of weeks. If the workaround works, I'll release 2.0 with BCM2835 support instead of `wiringpi`. If not, I'll patch the current version ASAP

**Comment by eshaham** [comment]
thanks @samsonmking 
I've managed to get it to work by switching to a GitHub clone of the project and compiling from the source.
Looking forward to seeing v2 💪

**Comment by samsonmking** [comment]
@eshaham glad to hear you got it working! I've updated the installation steps in the README. Now that `wiringpi` is removed from the apt repositories, we'll just default to the `deb` package (until v2)
I'm going to close this issue for now, but please let me know if you run into any more trouble.
