### ISSUE TITLE
inline JS in example

### ISSUE THREAD

**Issue by JohnMcLear** [samsonmking/epaper.js#8]
It makes sense for simplicities sake to have inline JS in an example html file but be mindful if people copy/paste it will cause inline javascript issues down the road for them.

I guess maybe a warning not to include the JS in the HTML is one solution?  Another is to have it another file?  Another is to disregard this and hope that the developers know what they are doing :P  

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_inline_script

**Comment by samsonmking** [comment]
Thanks for the feedback! My original intention was to try to keep the examples as simple / compact as possible, which is why I leaned towards keeping everything in a single file (in-lining). I know it might not be the best practice for a production web app, but I'm not sure it's as much of a concern here. The ePaper.js apps will only be running on localhost on a Raspberry Pi and not exposed to the internet. I'm going to close this issue for now and it can always be reconsidered, later, if the use cases increase in scope.
